require 'test_helper'

class TestTransformationResearchOutput < Minitest::Test

  def test_research_output_1
    # type: Journal article
    # id: 61faf216-1a25-4f01-8055-a44962120ee7
    # title: Can poly-parameter linear-free energy relationships (pp-LFERs) improve modelling bioaccumulation in fish?
    # keywords: Partition coefficients, pp-LFER, Bioaccumulation, Biotransformation
    # uri: http://dx.doi.org/10.1016/j.chemosphere.2017.10.007
    id = '9a95beaf-96e6-41a2-98f8-ba060d677522'
    transformer = ResearchMetadataAnnouncement::Transformer::ResearchOutput.new config
    announcement = transformer.transform id: id

    assert_equal 'New journal article. Can poly-parameter linear-free energy relationships (pp-LFERs) improve modelling bioaccumulation in fish? #partitioncoefficients #pplfer. dx.doi.org/10.1016/j.chemosphere.2017.10.007.', announcement
  end

  def test_research_output_2
    # type: Journal article
    # id: 61faf216-1a25-4f01-8055-a44962120ee7
    # title: The Parting of Burroughs and Kerouac
    # keywords: American Counterculture, Arthur Rimbaud, Poetic Realism, French Film
    # uri: http://dx.doi.org/10.1179/1477570013Z.00000000045
    id = '61faf216-1a25-4f01-8055-a44962120ee7'
    transformer = ResearchMetadataAnnouncement::Transformer::ResearchOutput.new config
    announcement = transformer.transform id: id, max_length: 140

    assert_equal 'New journal article. The Parting of Burroughs and Ker... #americancounterculture #arthurrimbaud. dx.doi.org/10.1179/1477570013Z.00000000045.', announcement
  end

  def test_research_output_3
    # type: Conference paper
    # id: ee1348d8-72a3-43de-aff8-96b09a5b897c
    # title: Deductive and inductive data collection for agent-based modelling
    # keywords: None
    # uri: None
    id = 'ee1348d8-72a3-43de-aff8-96b09a5b897c'
    transformer = ResearchMetadataAnnouncement::Transformer::ResearchOutput.new config
    announcement = transformer.transform id: id, composition: [:new, :title, :hashtags]

    assert_equal 'New conference paper. Deductive and inductive data collection for agent-based modelling.', announcement
  end

  def test_research_output_4
    # type: Journal article
    # id: 746c1eb5-cc46-43f4-aa8c-a39ca0064ea2
    # title: Torsion pairs in a triangulated category generated by a spherical object
    # keywords: Auslander–Reiten theory, Calabi–Yau triangulated category, Spherical object, Ptolemy arc, Torsion pair
    # uri: http://dx.doi.org/10.1016/j.jalgebra.2015.09.011
    id = '746c1eb5-cc46-43f4-aa8c-a39ca0064ea2'
    transformer = ResearchMetadataAnnouncement::Transformer::ResearchOutput.new config
    announcement = transformer.transform id: id, composition: [:new, :title, :keywords, :uri]

    assert_equal 'New journal article. Torsion pairs in a triangulated category generated by a spherical object. Auslander–Reiten theory, Calabi–Yau triangulated category. dx.doi.org/10.1016/j.jalgebra.2015.09.011.', announcement
  end

end